### ISSUE TITLE
AttributeError: Can't pickle local object 'get_transform.<locals>.<lambda>'

### ISSUE THREAD

**Issue by klbc-zz** [FFFROZEN090/Improved_CycleGAN_Staining#1]
Hello, I encountered the above exception while using your code for training. How can I resolve it? The running instructions are as follows
python train.py --.\datasets\olddraw\cycleGan --name exp_olddraw_c --batch_size 2  --model seg_cycle_gan --display_id 1

**Comment by FFFROZEN090** [comment]
> Hello, I encountered the above exception while using your code for training. How can I resolve it? The running instructions are as follows python train.py --.\datasets\olddraw\cycleGan --name exp_olddraw_c --batch_size 2 --model seg_cycle_gan --display_id 1

Hi, Thanks for approaching. Could you please provide more error log for addressing this issue?

**Comment by klbc-zz** [comment]
The above issue was resolved when I set the parameter num_threads to 0, but other errors occurred as follows


`UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    model.set_input(data)         # unpack data from dataset and apply preprocessing
  File "E:\code\python\aiProjects\biyesheji\git\Improved_CycleGAN_Staining\models\seg_cycle_gan_model.py", line 113, in set_input
    self.real_A_GT = input['A_GT'].to(self.device)
KeyError: 'A_GT'
`

**Comment by FFFROZEN090** [comment]
> The above issue was resolved when I set the parameter num_threads to 0, but other errors occurred as follows
> 
> `UserWarning: Detected call of `lr_scheduler.step()`before`optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()`before`lr_scheduler.step()`. Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate warnings.warn("Detected call of `lr_scheduler.step()`before`optimizer.step()`. " Traceback (most recent call last): File "train.py", line 54, in <module> model.set_input(data) # unpack data from dataset and apply preprocessing File "E:\code\python\aiProjects\biyesheji\git\Improved_CycleGAN_Staining\models\seg_cycle_gan_model.py", line 113, in set_input self.real_A_GT = input['A_GT'].to(self.device) KeyError: 'A_GT' `

Because my project is a improved method specific for Cell Segmentation dataset colorization, so a A_GT is needed. If you need a general and stable cycle gan project, please check https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix. All my works are on top of this resource.
